version: '3.8'
services:
  #POSTGRES SERVICE
  db:
    container_name: postgresql
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=fsw_barber
    ports:
      - 5433:5432
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network

  #PG ADMIN
  dbms:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=adm@fsw.barber.com
      - PGADMIN_DEFAULT_PASSWORD=dev
    user: root
    ports:
      - 5050:80
    volumes:
      - ./.docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - dev-network

# INTERNAL NETWORK
networks:
  dev-network:
    driver: bridge